# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff533a1b1646b5aa3a04d8c495d0467c289c0964e0f0cacd68f8cb2cf36ef254ff2729763a63ad5fce7bbc8281f38f62145fe7e807dbccb131c0d95e3a0f394e

test:
  secret_key_base: f5060bcd5bdaded1b6aac2204d4e12779bb73a89d2117bf2e8367dce2dc49ce23b30ac9baf3310e018ce0384d3badef9b498c15eae41344c26e375db0bc4d685

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
